//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.02 at 10:55:03 AM CST 
//


package com.imcs.syed.product;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.imcs.syed.product package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetProductsByNameResponse_QNAME = new QName("http://syed.imcs.com/Product", "getProductsByNameResponse");
    private final static QName _GetProductsByNameAndCategoryRequest_QNAME = new QName("http://syed.imcs.com/Product", "getProductsByNameAndCategoryRequest");
    private final static QName _CreateOrderResponse_QNAME = new QName("http://syed.imcs.com/Product", "createOrderResponse");
    private final static QName _GetProductsByNameRequest_QNAME = new QName("http://syed.imcs.com/Product", "getProductsByNameRequest");
    private final static QName _GetProductsByNameAndCategoryResponse_QNAME = new QName("http://syed.imcs.com/Product", "getProductsByNameAndCategoryResponse");
    private final static QName _GetAllProductsRequest_QNAME = new QName("http://syed.imcs.com/Product", "getAllProductsRequest");
    private final static QName _GetAllProductsResponse_QNAME = new QName("http://syed.imcs.com/Product", "getAllProductsResponse");
    private final static QName _CreateOrderRequest_QNAME = new QName("http://syed.imcs.com/Product", "createOrderRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.imcs.syed.product
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductsByNameRequest }
     * 
     */
    public GetProductsByNameRequest createGetProductsByNameRequest() {
        return new GetProductsByNameRequest();
    }

    /**
     * Create an instance of {@link GetProductsByNameAndCategoryResponse }
     * 
     */
    public GetProductsByNameAndCategoryResponse createGetProductsByNameAndCategoryResponse() {
        return new GetProductsByNameAndCategoryResponse();
    }

    /**
     * Create an instance of {@link GetProductsByNameResponse }
     * 
     */
    public GetProductsByNameResponse createGetProductsByNameResponse() {
        return new GetProductsByNameResponse();
    }

    /**
     * Create an instance of {@link GetProductsByNameAndCategoryRequest }
     * 
     */
    public GetProductsByNameAndCategoryRequest createGetProductsByNameAndCategoryRequest() {
        return new GetProductsByNameAndCategoryRequest();
    }

    /**
     * Create an instance of {@link CreateOrderResponse }
     * 
     */
    public CreateOrderResponse createCreateOrderResponse() {
        return new CreateOrderResponse();
    }

    /**
     * Create an instance of {@link CreateOrderRequest }
     * 
     */
    public CreateOrderRequest createCreateOrderRequest() {
        return new CreateOrderRequest();
    }

    /**
     * Create an instance of {@link GetAllProductsRequest }
     * 
     */
    public GetAllProductsRequest createGetAllProductsRequest() {
        return new GetAllProductsRequest();
    }

    /**
     * Create an instance of {@link GetAllProductsResponse }
     * 
     */
    public GetAllProductsResponse createGetAllProductsResponse() {
        return new GetAllProductsResponse();
    }

    /**
     * Create an instance of {@link Order }
     * 
     */
    public Order createOrder() {
        return new Order();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductsByNameResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syed.imcs.com/Product", name = "getProductsByNameResponse")
    public JAXBElement<GetProductsByNameResponse> createGetProductsByNameResponse(GetProductsByNameResponse value) {
        return new JAXBElement<GetProductsByNameResponse>(_GetProductsByNameResponse_QNAME, GetProductsByNameResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductsByNameAndCategoryRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syed.imcs.com/Product", name = "getProductsByNameAndCategoryRequest")
    public JAXBElement<GetProductsByNameAndCategoryRequest> createGetProductsByNameAndCategoryRequest(GetProductsByNameAndCategoryRequest value) {
        return new JAXBElement<GetProductsByNameAndCategoryRequest>(_GetProductsByNameAndCategoryRequest_QNAME, GetProductsByNameAndCategoryRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrderResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syed.imcs.com/Product", name = "createOrderResponse")
    public JAXBElement<CreateOrderResponse> createCreateOrderResponse(CreateOrderResponse value) {
        return new JAXBElement<CreateOrderResponse>(_CreateOrderResponse_QNAME, CreateOrderResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductsByNameRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syed.imcs.com/Product", name = "getProductsByNameRequest")
    public JAXBElement<GetProductsByNameRequest> createGetProductsByNameRequest(GetProductsByNameRequest value) {
        return new JAXBElement<GetProductsByNameRequest>(_GetProductsByNameRequest_QNAME, GetProductsByNameRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProductsByNameAndCategoryResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syed.imcs.com/Product", name = "getProductsByNameAndCategoryResponse")
    public JAXBElement<GetProductsByNameAndCategoryResponse> createGetProductsByNameAndCategoryResponse(GetProductsByNameAndCategoryResponse value) {
        return new JAXBElement<GetProductsByNameAndCategoryResponse>(_GetProductsByNameAndCategoryResponse_QNAME, GetProductsByNameAndCategoryResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syed.imcs.com/Product", name = "getAllProductsRequest")
    public JAXBElement<GetAllProductsRequest> createGetAllProductsRequest(GetAllProductsRequest value) {
        return new JAXBElement<GetAllProductsRequest>(_GetAllProductsRequest_QNAME, GetAllProductsRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAllProductsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syed.imcs.com/Product", name = "getAllProductsResponse")
    public JAXBElement<GetAllProductsResponse> createGetAllProductsResponse(GetAllProductsResponse value) {
        return new JAXBElement<GetAllProductsResponse>(_GetAllProductsResponse_QNAME, GetAllProductsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateOrderRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://syed.imcs.com/Product", name = "createOrderRequest")
    public JAXBElement<CreateOrderRequest> createCreateOrderRequest(CreateOrderRequest value) {
        return new JAXBElement<CreateOrderRequest>(_CreateOrderRequest_QNAME, CreateOrderRequest.class, null, value);
    }

}
